### ISSUE TITLE
[RN 0.61.5] Invariant Violation: Maximum update depth exceeded

### ISSUE THREAD

**Issue by nabilfreeman** [TaylorBriggs/react-native-typewriter#36] opened 2020-04-01 15:41 UTC
Hi there, been using this plugin for a couple of years at https://github.com/lesalonapp. Worked great up to 0.59. Currently upgrading and ran into this crash.

<img width="906" alt="Screenshot 2020-04-01 at 16 39 19" src="https://user-images.githubusercontent.com/2470659/78157066-7305ba80-7437-11ea-9737-92672c1398a7.png">

I'll try and debug & report the underlying issue here.

**Comment by nabilfreeman** [comment] 2020-04-01 16:11
Removed it from project 😞was a small UI thing that we might restore after the upgrade.

I think it was an issue with the typing continuing after the component unmounted but ran out of time to debug.

**Comment by TaylorBriggs** [comment] 2020-04-05 19:49
Should be fixed with #37. It'll be published as 0.7.0. I noticed the `timeoutId` wasn't getting unset when the timer gets cleared, which I think is the cause of the problem.

**Closed as completed** 2020-04-05 19:49 UTC

**Comment by nabilfreeman** [comment] 2020-04-13 23:30
Thanks @TaylorBriggs! Really appreciate you acting fast on the plugin. I'll give it another try once I've finished the upgrade (2 weeks on, still going 😱)
